import psycopg2
conn = psycopg2.connect('postgresql://postgres:Postgres2024!@127.0.0.1:5433/aiplaning_local')
conn.autocommit = True
cur = conn.cursor()

tables = [
    'sap_produccion', 
    'sap_stock_mb52', 
    'sap_programa_produccion', 
    'sap_demanda_proyectada', 
    'sap_consumo_diario_clean', 
    'sap_pronostico_diario', 
    'sync_status_log'
]

for t in tables:
    try:
        print(f"Buscando MAX(id) en {t}...")
        cur.execute(f"SELECT COALESCE(MAX(id), 0) FROM {t}")
        max_id = cur.fetchone()[0]
        
        # Alterar la columna id a GENERATED BY DEFAULT AS IDENTITY
        try:
            cur.execute(f"ALTER TABLE {t} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
            print(f" -> Columna 'id' de {t} alterada a IDENTITY.")
        except Exception as alter_err:
            if "already an identity column" in str(alter_err) or "ya es una columna identidad" in str(alter_err):
                print(f" -> {t} ya tiene columna IDENTITY. Continuando...")
            else:
                raise alter_err

        # Resetear secuencia
        cur.execute(f"SELECT setval(pg_get_serial_sequence('{t}', 'id'), {max_id + 1}, false)")
        print(f" -> Secuencia reseteada a {max_id + 1}")
        
    except Exception as e:
        print(f"Error procesando {t}: {e}")

cur.close()
conn.close()
print("Proceso completado.")
